--- 
global: 
  evaluation_interval: 15s
  external_labels: 
    monitor: go_app
  scrape_interval: 15s
rule_files: 
  - prometheus.rules.yml
scrape_configs: 
  - 
    job_name: prometheus
    scrape_interval: 5s
    static_configs: 
      - 
        targets: 
          - "localhost:9090"
  - 
    job_name: go_app
    scrape_interval: 5s
    static_configs: 
      - 
        labels: 
          group: production
        targets: 
          - "localhost:10010"